apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dummy-deployment
  name: dummy-deployment
  namespace: konflux-dummy-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dummy-deployment
  template:
    metadata:
      labels:
        app: dummy-deployment
    spec:
      containers:
      - env:
        - name: DISPLAY_TEXT
          valueFrom:
            configMapKeyRef:
              key: DISPLAY_TEXT
              name: dummy-deployment-config
        image: quay.io/redhat-appstudio-qe/dummy-deployment:33f3601c93bcf0ad62d4cc6cfaf8df9d4d224011
        name: dummy-deployment
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 50m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 16Mi
        securityContext:
          readOnlyRootFilesystem: true
          runAsNonRoot: true
