apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- https://github.com/flacatus/konflux-dummy-deploy//k8s?ref=cd906fbd79998582a680768b8dc52c99c33dc233
images:
- name: quay.io/redhat-appstudio-qe/dummy-deployment
  newTag: cd906fbd79998582a680768b8dc52c99c33dc233
patches:
- target:
    kind: ConfigMap
    name: dummy-deployment-config
  patch: |
    - op: replace
      path: /data/DISPLAY_TEXT
      value: "Hello from STAGE!"
